networks:
  back-tier:
  back-public-tier:
  front-tier:

volumes:
  db-data:

services:
  db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_HOST
      - POSTGRES_PORT
    networks:
      - back-tier

  backend:
    image: naucto-dev-backend
    build:
      context: dev_environment/backend
      args:
        BACKEND_PORT: ${BACKEND_PORT}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_HOST: ${POSTGRES_HOST}
        POSTGRES_PORT: ${POSTGRES_PORT}
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_HOST
      - POSTGRES_PORT
      - BACKEND_PORT
      - JWT_SECRET
      - JWT_EXPIRES_IN
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION
    networks:
      - back-tier
      - back-public-tier
      - front-tier
    depends_on:
      - db

  frontend:
    image: naucto-dev-frontend
    build:
      context: dev_environment/frontend
      args:
        FRONTEND_PORT: ${FRONTEND_PORT}
    environment:
      - VITE_BACKEND_URL=https://${SSL_TARGET_DOMAIN}:${BACKEND_PORT}/
    networks:
      - front-tier
    volumes:
      - ${FRONTEND_CONFIG_PATH}:/app/config.json:ro
    depends_on:
      - backend

  ssl_proxy_frontend:
    image: fsouza/docker-ssl-proxy
    environment:
      - DOMAIN=${SSL_TARGET_DOMAIN}
      - TARGET_PORT=${FRONTEND_PORT}
      - TARGET_HOST=frontend
    networks:
      - front-tier
    volumes:
      - ${SSL_CERTS_PATH}/fullchain.pem:/etc/nginx/certs/cert.pem:ro
      - ${SSL_CERTS_PATH}/privkey.pem:/etc/nginx/certs/key.pem:ro
    depends_on:
      - frontend

  ssl_proxy_backend:
    image: fsouza/docker-ssl-proxy
    environment:
      - DOMAIN=${SSL_TARGET_DOMAIN}
      - TARGET_PORT=${FRONTEND_PORT}
      - TARGET_HOST=backend
    networks:
      - back-public-tier
    volumes:
      - ${SSL_CERTS_PATH}/fullchain.pem:/etc/nginx/certs/cert.pem:ro
      - ${SSL_CERTS_PATH}/privkey.pem:/etc/nginx/certs/key.pem:ro
    depends_on:
      - backend
