/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["AuthController_login"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/refresh": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["AuthController_refresh"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["AuthController_logout"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["AuthController_me"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/deployments": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["DeploymentsController_list"];
    put?: never;
    post: operations["DeploymentsController_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/deployments/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["DeploymentsController_get"];
    put?: never;
    post?: never;
    delete: operations["DeploymentActionsController_remove"];
    options?: never;
    head?: never;
    patch: operations["DeploymentsController_update"];
    trace?: never;
  };
  "/deployments/{id}/env": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["EnvVarsController_list"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/deployments/{id}/env/{key}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put: operations["EnvVarsController_set"];
    post?: never;
    delete: operations["EnvVarsController_remove"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/deployments/{id}/deploy": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["DeploymentActionsController_deploy"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/deployments/{id}/stop": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["DeploymentActionsController_stop"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/deployments/{id}/start": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["DeploymentActionsController_start"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/deployments/{id}/releases": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["DeploymentActionsController_listReleases"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/releases/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["DeploymentActionsController_getRelease"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/deployments/{id}/webhook": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["WebhooksController_status"];
    put?: never;
    post: operations["WebhooksController_rotate"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    LoginDto: {
      /** Format: email */
      email: string;
      password: string;
    };
    SessionUserDto: {
      /** Format: uuid */
      id: string;
      /** Format: email */
      email: string;
      /** @enum {string} */
      role: "ADMIN" | "OPERATOR" | "VIEWER";
    };
    SessionDto: {
      accessToken: string;
      refreshToken: string;
      user: components["schemas"]["SessionUserDto"];
    };
    OkResponseDto: {
      /** @example true */
      ok: boolean;
    };
    AuthUserDto: {
      /** Format: uuid */
      userId: string;
      /** Format: email */
      email: string;
      /** @enum {string} */
      role: "ADMIN" | "OPERATOR" | "VIEWER";
    };
    CreateDeploymentDto: {
      /** @example my-app */
      name: string;
      /** @enum {string} */
      type: "WEB" | "WORKER" | "CRON";
      /** @example https://github.com/owner/repo.git */
      gitUrl: string;
      /** @example main */
      gitRef?: string;
      /** @enum {string} */
      buildStrategy?: "NIXPACKS" | "DOCKERFILE" | "COMPOSE";
      dockerfilePath?: string;
      webServicePort?: number;
      /** @example / */
      healthCheckPath?: string;
      runCommand?: string;
      /** @example 0 3 * * * */
      cronExpr?: string;
      /** @example app.example.com */
      domain?: string;
      /** @description Personal access token for a private repo (encrypted at rest). */
      gitToken?: string;
      memoryLimitMb?: number;
    };
    DeploymentDto: {
      /** Format: uuid */
      id: string;
      name: string;
      /** @enum {string} */
      type: "WEB" | "WORKER" | "CRON";
      gitUrl: string;
      gitRef: string;
      /** @enum {string} */
      buildStrategy: "NIXPACKS" | "DOCKERFILE" | "COMPOSE";
      dockerfilePath: string | null;
      composeFilePath: string | null;
      composeWebService: string | null;
      runCommand: string | null;
      cronExpr: string | null;
      webServicePort: number | null;
      healthCheckPath: string;
      autoDeploy: boolean;
      /** @enum {string} */
      restartPolicy: "NO" | "ON_FAILURE" | "ALWAYS" | "UNLESS_STOPPED";
      memoryLimitMb: number | null;
      nanoCpus: number | null;
      /** @enum {string} */
      state: "CREATED" | "DEPLOYING" | "RUNNING" | "DEGRADED" | "STOPPED" | "ERROR";
      /** Format: uuid */
      activeReleaseId: string | null;
      /** Format: uuid */
      gitCredentialId: string | null;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    UpdateDeploymentDto: {
      gitUrl?: string;
      gitRef?: string;
      /** @enum {string} */
      buildStrategy?: "NIXPACKS" | "DOCKERFILE" | "COMPOSE";
      dockerfilePath?: string;
      webServicePort?: number;
      healthCheckPath?: string;
      runCommand?: string;
      cronExpr?: string;
      autoDeploy?: boolean;
      /** @enum {string} */
      restartPolicy?: "NO" | "ON_FAILURE" | "ALWAYS" | "UNLESS_STOPPED";
      memoryLimitMb?: number;
    };
    MaskedEnvVarDto: {
      key: string;
      /** @enum {string} */
      scope: "BUILD" | "RUNTIME" | "BOTH";
      isSecret: boolean;
    };
    SetEnvVarDto: {
      value: string;
      /** @enum {string} */
      scope?: "BUILD" | "RUNTIME" | "BOTH";
      isSecret?: boolean;
    };
    ReleaseDto: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      deploymentId: string;
      gitSha: string | null;
      imageTag: string | null;
      /** @enum {string} */
      status:
        | "QUEUED"
        | "CLONING"
        | "BUILDING"
        | "HEALTHCHECKING"
        | "LIVE"
        | "SUPERSEDED"
        | "FAILED"
        | "ROLLEDBACK"
        | "INTERRUPTED";
      containerId: string | null;
      composeProject: string | null;
      logPath: string | null;
      errorMessage: string | null;
      /** Format: uuid */
      createdById: string | null;
      /** Format: date-time */
      queuedAt: string;
      /** Format: date-time */
      startedAt: string | null;
      /** Format: date-time */
      finishedAt: string | null;
      /** Format: date-time */
      createdAt: string;
    };
    WebhookStatusDto: {
      configured: boolean;
      path: string;
    };
    WebhookSecretDto: {
      secret: string;
      path: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  AuthController_login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginDto"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SessionDto"];
        };
      };
    };
  };
  AuthController_refresh: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SessionDto"];
        };
      };
    };
  };
  AuthController_logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OkResponseDto"];
        };
      };
    };
  };
  AuthController_me: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthUserDto"];
        };
      };
    };
  };
  DeploymentsController_list: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DeploymentDto"][];
        };
      };
    };
  };
  DeploymentsController_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateDeploymentDto"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DeploymentDto"];
        };
      };
    };
  };
  DeploymentsController_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DeploymentDto"];
        };
      };
    };
  };
  DeploymentActionsController_remove: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OkResponseDto"];
        };
      };
    };
  };
  DeploymentsController_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateDeploymentDto"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DeploymentDto"];
        };
      };
    };
  };
  EnvVarsController_list: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MaskedEnvVarDto"][];
        };
      };
    };
  };
  EnvVarsController_set: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        key: string;
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SetEnvVarDto"];
      };
    };
    responses: {
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  EnvVarsController_remove: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        key: string;
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  DeploymentActionsController_deploy: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReleaseDto"];
        };
      };
    };
  };
  DeploymentActionsController_stop: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OkResponseDto"];
        };
      };
    };
  };
  DeploymentActionsController_start: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OkResponseDto"];
        };
      };
    };
  };
  DeploymentActionsController_listReleases: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReleaseDto"][];
        };
      };
    };
  };
  DeploymentActionsController_getRelease: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReleaseDto"];
        };
      };
    };
  };
  WebhooksController_status: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["WebhookStatusDto"];
        };
      };
    };
  };
  WebhooksController_rotate: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["WebhookSecretDto"];
        };
      };
    };
  };
}
