/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/users": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["UsersController_list"];
    put?: never;
    post: operations["UsersController_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/users/{id}/role": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations["UsersController_setRole"];
    trace?: never;
  };
  "/users/{id}/password": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations["UsersController_setPassword"];
    trace?: never;
  };
  "/users/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations["UsersController_remove"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["AuthController_login"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/refresh": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["AuthController_refresh"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["AuthController_logout"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["AuthController_me"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/deployments": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["DeploymentsController_list"];
    put?: never;
    post: operations["DeploymentsController_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/deployments/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["DeploymentsController_get"];
    put?: never;
    post?: never;
    delete: operations["DeploymentActionsController_remove"];
    options?: never;
    head?: never;
    patch: operations["DeploymentsController_update"];
    trace?: never;
  };
  "/deployments/{id}/domains": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["DeploymentsController_domains"];
    put?: never;
    post: operations["DeploymentsController_addDomain"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/deployments/{id}/domains/{domainId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations["DeploymentsController_removeDomain"];
    options?: never;
    head?: never;
    patch: operations["DeploymentsController_updateDomainTarget"];
    trace?: never;
  };
  "/deployments/{id}/domains/{domainId}/primary": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations["DeploymentsController_makeDomainPrimary"];
    trace?: never;
  };
  "/deployments/{id}/services/{service}/resources": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["DeploymentsController_serviceResources"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations["DeploymentsController_setServiceResources"];
    trace?: never;
  };
  "/deployments/{id}/env": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["EnvVarsController_list"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/deployments/{id}/env/{key}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put: operations["EnvVarsController_set"];
    post?: never;
    delete: operations["EnvVarsController_remove"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/deployments/{id}/run": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["DeploymentActionsController_run"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/deployments/{id}/cron-runs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["DeploymentActionsController_cronRunHistory"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/deployments/{id}/deploy": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["DeploymentActionsController_deploy"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/deployments/{id}/stop": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["DeploymentActionsController_stop"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/deployments/{id}/start": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["DeploymentActionsController_start"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/deployments/{id}/restart": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["DeploymentActionsController_restart"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/deployments/{id}/rollback/{releaseId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["DeploymentActionsController_rollback"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/deployments/{id}/releases": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["DeploymentActionsController_listReleases"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/deployments/{id}/releases/{releaseId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations["DeploymentActionsController_deleteRelease"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/releases/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["DeploymentActionsController_getRelease"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/deployments/{id}/webhook": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["WebhooksController_status"];
    put?: never;
    post: operations["WebhooksController_rotate"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/streams/ticket": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["ConsoleController_ticket"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/system/info": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["SystemController_info"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/system/public-ip": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["SystemController_publicIp"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/dns/zones": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["DnsController_zones"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/dns/zones/{zone}/records": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["DnsController_records"];
    put?: never;
    post: operations["DnsController_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/dns/zones/{zone}/records/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put: operations["DnsController_update"];
    post?: never;
    delete: operations["DnsController_remove"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/backups": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["BackupsController_list"];
    put?: never;
    post: operations["BackupsController_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/backups/volumes": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["BackupsController_volumes"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/backups/{id}/restore": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["BackupsController_restore"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/backups/{id}/push/{destinationId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["BackupsController_push"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/backups/{id}/download": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["BackupsController_download"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/backups/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations["BackupsController_remove"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/backups/schedules": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["BackupSchedulesController_list"];
    put?: never;
    post: operations["BackupSchedulesController_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/backups/schedules/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations["BackupSchedulesController_remove"];
    options?: never;
    head?: never;
    patch: operations["BackupSchedulesController_setEnabled"];
    trace?: never;
  };
  "/backups/destinations": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["BackupDestinationsController_list"];
    put?: never;
    post: operations["BackupDestinationsController_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/backups/destinations/test": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["BackupDestinationsController_test"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/backups/destinations/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations["BackupDestinationsController_remove"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/deployments/{id}/containers": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["DeploymentVolumesController_list"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/deployments/{id}/volumes/{name}/reset": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["DeploymentVolumesController_reset"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    UserDto: {
      /** Format: uuid */
      id: string;
      email: string;
      /** @enum {string} */
      role: "ADMIN" | "OPERATOR" | "VIEWER";
      /** Format: date-time */
      createdAt: string;
    };
    CreateUserDto: {
      /** Format: email */
      email: string;
      password: string;
      /** @enum {string} */
      role: "ADMIN" | "OPERATOR" | "VIEWER";
    };
    UpdateUserRoleDto: {
      /** @enum {string} */
      role: "ADMIN" | "OPERATOR" | "VIEWER";
    };
    SetPasswordDto: {
      password: string;
    };
    OkResponseDto: {
      /** @example true */
      ok: boolean;
    };
    LoginDto: {
      /** Format: email */
      email: string;
      password: string;
    };
    SessionUserDto: {
      /** Format: uuid */
      id: string;
      /** Format: email */
      email: string;
      /** @enum {string} */
      role: "ADMIN" | "OPERATOR" | "VIEWER";
    };
    SessionDto: {
      accessToken: string;
      refreshToken: string;
      user: components["schemas"]["SessionUserDto"];
    };
    AuthUserDto: {
      /** Format: uuid */
      userId: string;
      /** Format: email */
      email: string;
      /** @enum {string} */
      role: "ADMIN" | "OPERATOR" | "VIEWER";
    };
    CreateDeploymentDto: {
      /** @example my-app */
      name: string;
      /** @enum {string} */
      type: "WEB" | "WORKER" | "CRON";
      /** @example https://github.com/owner/repo.git */
      gitUrl?: string;
      /** @example main */
      gitRef?: string;
      /**
       * @description For the IMAGE strategy.
       * @example nginx:1.27
       */
      imageRef?: string;
      /** @enum {string} */
      buildStrategy?: "NIXPACKS" | "DOCKERFILE" | "COMPOSE" | "IMAGE";
      dockerfilePath?: string;
      /** @example docker-compose.yml */
      composeFilePath?: string;
      /** @description Compose service to route + monitor. */
      composeWebService?: string;
      webServicePort?: number;
      /** @example / */
      healthCheckPath?: string;
      runCommand?: string;
      /** @example 0 3 * * * */
      cronExpr?: string;
      /** @example app.example.com */
      domain?: string;
      /** @description Personal access token for a private repo (encrypted at rest). */
      gitToken?: string;
      memoryLimitMb?: number;
      /** @description CPU limit in nano-CPUs (1 CPU = 1e9) */
      nanoCpus?: number;
      /**
       * @example [
       *       "NET_ADMIN"
       *     ]
       */
      capAdd?: string[];
      /**
       * @example [
       *       "ALL"
       *     ]
       */
      capDrop?: string[];
    };
    StrategyConfigDto: {
      dockerfilePath?: string;
      composeFilePath?: string;
      composeWebService?: string;
      imageRef?: string;
    };
    DeploymentDto: {
      /** Format: uuid */
      id: string;
      name: string;
      /** @enum {string} */
      type: "WEB" | "WORKER" | "CRON";
      gitUrl: string;
      gitRef: string;
      /** @enum {string} */
      buildStrategy: "NIXPACKS" | "DOCKERFILE" | "COMPOSE" | "IMAGE";
      strategyConfig: components["schemas"]["StrategyConfigDto"];
      runCommand: string | null;
      cronExpr: string | null;
      webServicePort: number | null;
      healthCheckPath: string;
      autoDeploy: boolean;
      /** @enum {string} */
      restartPolicy: "NO" | "ON_FAILURE" | "ALWAYS" | "UNLESS_STOPPED";
      memoryLimitMb: number | null;
      nanoCpus: number | null;
      capAdd: string[] | null;
      capDrop: string[] | null;
      logMaxSizeMb: number | null;
      logMaxFiles: number | null;
      /** @enum {string} */
      state: "CREATED" | "DEPLOYING" | "RUNNING" | "DEGRADED" | "STOPPED" | "ERROR";
      /** Format: uuid */
      activeReleaseId: string | null;
      /** Format: uuid */
      gitCredentialId: string | null;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
      primaryDomain: string | null;
    };
    UpdateDeploymentDto: {
      gitUrl?: string;
      /** @example nginx:1.27 */
      imageRef?: string;
      gitRef?: string;
      /** @enum {string} */
      buildStrategy?: "NIXPACKS" | "DOCKERFILE" | "COMPOSE" | "IMAGE";
      dockerfilePath?: string;
      composeFilePath?: string;
      composeWebService?: string;
      webServicePort?: number;
      healthCheckPath?: string;
      runCommand?: string;
      cronExpr?: string;
      autoDeploy?: boolean;
      /** @enum {string} */
      restartPolicy?: "NO" | "ON_FAILURE" | "ALWAYS" | "UNLESS_STOPPED";
      memoryLimitMb?: number | null;
      /** @description CPU limit in nano-CPUs (1 CPU = 1e9) */
      nanoCpus?: number | null;
      /**
       * @example [
       *       "NET_ADMIN"
       *     ]
       */
      capAdd?: string[];
      /**
       * @example [
       *       "ALL"
       *     ]
       */
      capDrop?: string[];
      /** @example 10 */
      logMaxSizeMb?: number | null;
      /** @example 3 */
      logMaxFiles?: number | null;
      /** @example app.example.com */
      domain?: string;
    };
    DomainDto: {
      /** Format: uuid */
      id: string;
      fqdn: string;
      isPrimary: boolean;
      /** @description Compose service this domain routes to; null = the deployment's default container. */
      targetService: string | null;
      /** @description Internal port this domain routes to; null = the deployment's web service port. */
      targetPort: number | null;
    };
    AddDomainDto: {
      /** @example app.example.com */
      fqdn: string;
      /** @example frontend */
      targetService?: string | null;
      /** @example 8080 */
      targetPort?: number | null;
    };
    UpdateDomainTargetDto: {
      /** @example frontend */
      targetService?: string | null;
      /** @example 8080 */
      targetPort?: number | null;
    };
    ResourceLimitsDto: {
      /** @example 512 */
      memoryLimitMb?: number | null;
      /** @example 1000000000 */
      nanoCpus?: number | null;
      /**
       * @example [
       *       "NET_ADMIN"
       *     ]
       */
      capAdd?: string[];
      /**
       * @example [
       *       "ALL"
       *     ]
       */
      capDrop?: string[];
      /** @enum {string} */
      restartPolicy?: "NO" | "ON_FAILURE" | "ALWAYS" | "UNLESS_STOPPED";
      /** @example 10 */
      logMaxSizeMb?: number | null;
      /** @example 3 */
      logMaxFiles?: number | null;
    };
    MaskedEnvVarDto: {
      key: string;
      /** @enum {string} */
      scope: "BUILD" | "RUNTIME" | "BOTH";
      isSecret: boolean;
    };
    SetEnvVarDto: {
      value: string;
      /** @enum {string} */
      scope?: "BUILD" | "RUNTIME" | "BOTH";
      isSecret?: boolean;
    };
    CronRunDto: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      deploymentId: string;
      /** @enum {string} */
      status: "RUNNING" | "SUCCESS" | "FAILED";
      exitCode: number | null;
      logs: string | null;
      /** Format: date-time */
      startedAt: string;
      /** Format: date-time */
      finishedAt: string | null;
    };
    ReleaseDto: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      deploymentId: string;
      gitSha: string | null;
      imageTag: string | null;
      /** @enum {string} */
      status:
        | "QUEUED"
        | "CLONING"
        | "BUILDING"
        | "HEALTHCHECKING"
        | "LIVE"
        | "SUPERSEDED"
        | "FAILED"
        | "ROLLEDBACK"
        | "INTERRUPTED";
      containerId: string | null;
      composeProject: string | null;
      logPath: string | null;
      errorMessage: string | null;
      /** Format: uuid */
      createdById: string | null;
      /** Format: date-time */
      queuedAt: string;
      /** Format: date-time */
      startedAt: string | null;
      /** Format: date-time */
      finishedAt: string | null;
      /** Format: date-time */
      createdAt: string;
    };
    WebhookStatusDto: {
      configured: boolean;
      path: string;
    };
    WebhookSecretDto: {
      secret: string;
      path: string;
    };
    StreamTicketDto: {
      ticket: string;
    };
    SystemInfoDto: {
      version: string;
      commit: string;
      distro: string;
      kernel: string;
      platform: string;
      arch: string;
      node: string;
    };
    PublicIpDto: {
      ip: string | null;
    };
    ZonesDto: {
      zones: string[];
    };
    DnsRecordDto: {
      id: number;
      zone: string;
      fieldType: string;
      subDomain: string;
      target: string;
      ttl: number;
    };
    CreateDnsRecordDto: {
      /** @enum {string} */
      fieldType: "A" | "AAAA" | "CNAME" | "TXT" | "MX" | "NS" | "SRV";
      /** @example app */
      subDomain: string;
      /** @example 203.0.113.10 */
      target: string;
      /** @default 3600 */
      ttl: number;
    };
    UpdateDnsRecordDto: {
      target: string;
      ttl?: number;
      subDomain?: string;
    };
    BackupDto: {
      /** Format: uuid */
      id: string;
      deploymentId: string | null;
      /** @enum {string} */
      kind: "VOLUME_TAR" | "PG_DUMP" | "S3_SYNC";
      /** @enum {string} */
      status: "PENDING" | "RUNNING" | "SUCCESS" | "FAILED";
      target: string | null;
      sizeBytes: number | null;
      errorMessage: string | null;
      offsiteUrl: string | null;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      finishedAt: string | null;
    };
    VolumesDto: {
      volumes: string[];
    };
    CreateBackupDto: {
      /** @enum {string} */
      kind: "VOLUME_TAR" | "PG_DUMP" | "S3_SYNC";
      /** @example willy_compose-blog_data */
      target: string;
      /** Format: uuid */
      deploymentId?: string;
    };
    BackupScheduleDto: {
      /** Format: uuid */
      id: string;
      deploymentId: string | null;
      target: string;
      cron: string;
      retention: number;
      enabled: boolean;
      /** Format: date-time */
      lastRunAt: string | null;
      /** Format: date-time */
      createdAt: string;
    };
    CreateBackupScheduleDto: {
      /** @example willy_blog_data */
      target: string;
      /** @example 0 3 * * * */
      cron: string;
      /** @example 7 */
      retention?: number;
      /** Format: uuid */
      deploymentId?: string;
    };
    UpdateBackupScheduleDto: {
      enabled: boolean;
    };
    BackupDestinationDto: {
      /** Format: uuid */
      id: string;
      name: string;
      /** @enum {string} */
      type: "S3" | "FTP" | "SFTP" | "SSH";
      /** Format: date-time */
      createdAt: string;
    };
    CreateBackupDestinationDto: {
      /** @example offsite-s3 */
      name: string;
      /** @enum {string} */
      type: "S3" | "FTP" | "SFTP" | "SSH";
      bucket?: string;
      prefix?: string;
      region?: string;
      /** @example https://s3.example.com */
      endpoint?: string;
      accessKeyId?: string;
      secretAccessKey?: string;
      host?: string;
      port?: number;
      username?: string;
      password?: string;
      path?: string;
      privateKey?: string;
    };
    VolumeMountDto: {
      name: string;
      destination: string;
      rw: boolean;
    };
    NetworkInfoDto: {
      name: string;
      ip: string | null;
    };
    ContainerDto: {
      id: string;
      name: string;
      image: string;
      running: boolean;
      volumes: components["schemas"]["VolumeMountDto"][];
      service: string | null;
      networks: components["schemas"]["NetworkInfoDto"][];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  UsersController_list: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserDto"][];
        };
      };
    };
  };
  UsersController_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateUserDto"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserDto"];
        };
      };
    };
  };
  UsersController_setRole: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateUserRoleDto"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserDto"];
        };
      };
    };
  };
  UsersController_setPassword: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SetPasswordDto"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OkResponseDto"];
        };
      };
    };
  };
  UsersController_remove: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OkResponseDto"];
        };
      };
    };
  };
  AuthController_login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginDto"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SessionDto"];
        };
      };
    };
  };
  AuthController_refresh: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SessionDto"];
        };
      };
    };
  };
  AuthController_logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OkResponseDto"];
        };
      };
    };
  };
  AuthController_me: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthUserDto"];
        };
      };
    };
  };
  DeploymentsController_list: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DeploymentDto"][];
        };
      };
    };
  };
  DeploymentsController_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateDeploymentDto"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DeploymentDto"];
        };
      };
    };
  };
  DeploymentsController_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DeploymentDto"];
        };
      };
    };
  };
  DeploymentActionsController_remove: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OkResponseDto"];
        };
      };
    };
  };
  DeploymentsController_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateDeploymentDto"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DeploymentDto"];
        };
      };
    };
  };
  DeploymentsController_domains: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DomainDto"][];
        };
      };
    };
  };
  DeploymentsController_addDomain: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AddDomainDto"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DomainDto"];
        };
      };
    };
  };
  DeploymentsController_removeDomain: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        domainId: string;
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OkResponseDto"];
        };
      };
    };
  };
  DeploymentsController_updateDomainTarget: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        domainId: string;
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateDomainTargetDto"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DomainDto"];
        };
      };
    };
  };
  DeploymentsController_makeDomainPrimary: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        domainId: string;
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OkResponseDto"];
        };
      };
    };
  };
  DeploymentsController_serviceResources: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        service: string;
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ResourceLimitsDto"];
        };
      };
    };
  };
  DeploymentsController_setServiceResources: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        service: string;
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ResourceLimitsDto"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ResourceLimitsDto"];
        };
      };
    };
  };
  EnvVarsController_list: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MaskedEnvVarDto"][];
        };
      };
    };
  };
  EnvVarsController_set: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        key: string;
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SetEnvVarDto"];
      };
    };
    responses: {
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  EnvVarsController_remove: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        key: string;
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  DeploymentActionsController_run: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OkResponseDto"];
        };
      };
    };
  };
  DeploymentActionsController_cronRunHistory: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CronRunDto"][];
        };
      };
    };
  };
  DeploymentActionsController_deploy: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReleaseDto"];
        };
      };
    };
  };
  DeploymentActionsController_stop: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OkResponseDto"];
        };
      };
    };
  };
  DeploymentActionsController_start: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OkResponseDto"];
        };
      };
    };
  };
  DeploymentActionsController_restart: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OkResponseDto"];
        };
      };
    };
  };
  DeploymentActionsController_rollback: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        releaseId: string;
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OkResponseDto"];
        };
      };
    };
  };
  DeploymentActionsController_listReleases: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReleaseDto"][];
        };
      };
    };
  };
  DeploymentActionsController_deleteRelease: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        releaseId: string;
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OkResponseDto"];
        };
      };
    };
  };
  DeploymentActionsController_getRelease: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReleaseDto"];
        };
      };
    };
  };
  WebhooksController_status: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["WebhookStatusDto"];
        };
      };
    };
  };
  WebhooksController_rotate: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["WebhookSecretDto"];
        };
      };
    };
  };
  ConsoleController_ticket: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StreamTicketDto"];
        };
      };
    };
  };
  SystemController_info: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SystemInfoDto"];
        };
      };
    };
  };
  SystemController_publicIp: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PublicIpDto"];
        };
      };
    };
  };
  DnsController_zones: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ZonesDto"];
        };
      };
    };
  };
  DnsController_records: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        zone: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DnsRecordDto"][];
        };
      };
    };
  };
  DnsController_create: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        zone: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateDnsRecordDto"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DnsRecordDto"];
        };
      };
    };
  };
  DnsController_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
        zone: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateDnsRecordDto"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OkResponseDto"];
        };
      };
    };
  };
  DnsController_remove: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
        zone: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OkResponseDto"];
        };
      };
    };
  };
  BackupsController_list: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BackupDto"][];
        };
      };
    };
  };
  BackupsController_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateBackupDto"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BackupDto"];
        };
      };
    };
  };
  BackupsController_volumes: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["VolumesDto"];
        };
      };
    };
  };
  BackupsController_restore: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OkResponseDto"];
        };
      };
    };
  };
  BackupsController_push: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        destinationId: string;
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OkResponseDto"];
        };
      };
    };
  };
  BackupsController_download: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  BackupsController_remove: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OkResponseDto"];
        };
      };
    };
  };
  BackupSchedulesController_list: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BackupScheduleDto"][];
        };
      };
    };
  };
  BackupSchedulesController_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateBackupScheduleDto"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BackupScheduleDto"];
        };
      };
    };
  };
  BackupSchedulesController_remove: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OkResponseDto"];
        };
      };
    };
  };
  BackupSchedulesController_setEnabled: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateBackupScheduleDto"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BackupScheduleDto"];
        };
      };
    };
  };
  BackupDestinationsController_list: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BackupDestinationDto"][];
        };
      };
    };
  };
  BackupDestinationsController_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateBackupDestinationDto"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BackupDestinationDto"];
        };
      };
    };
  };
  BackupDestinationsController_test: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateBackupDestinationDto"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OkResponseDto"];
        };
      };
    };
  };
  BackupDestinationsController_remove: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OkResponseDto"];
        };
      };
    };
  };
  DeploymentVolumesController_list: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ContainerDto"][];
        };
      };
    };
  };
  DeploymentVolumesController_reset: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        name: string;
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OkResponseDto"];
        };
      };
    };
  };
}
